// Generated by CoffeeScript 1.6.3
(function() {
  var API_URL_BASE, LOGIN_PAGE_URL, Session, Work, makeQuery, pixiv, request;

  API_URL_BASE = "http://spapi.pixiv.net/iphone";

  LOGIN_PAGE_URL = "https://www.secure.pixiv.net/login.php";

  request = require("request");

  Session = require("./session");

  Work = require("./work").Work;

  makeQuery = function(obj) {
    var key;
    return ((function() {
      var _results;
      _results = [];
      for (key in obj) {
        _results.push("" + (encodeURIComponent(key)) + "=" + (encodeURIComponent(obj[key])));
      }
      return _results;
    })()).join("&");
  };

  pixiv = {
    config: {
      endpoints: {
        loginPageUrl: LOGIN_PAGE_URL,
        apiBaseUrl: API_URL_BASE
      }
    },
    createSession: function(userId, password, callback) {
      if (!callback) {
        callback = userId;
        userId = null;
      }
      userId = userId || process.env.PIXIV_ID;
      password = password || process.env.PIXIV_PASS;
      if (!(userId && password)) {
        callback("There is no authenticate data.");
        return;
      }
      return request.post({
        url: pixiv.config.endpoints.loginPageUrl,
        formData: {
          mode: "login",
          pixiv_id: userId,
          pass: password
        }
      }, function(error, resp, body) {
        var sessId, sessSetCookie, setCookies;
        if (error) {
          callback(error);
        }
        setCookies = resp.headers["set-cookie"];
        if (!setCookies) {
          callback("failed to login.");
          return;
        }
        sessSetCookie = (setCookies.filter(function(c, i) {
          return (c.indexOf("PHPSESSID")) === 0;
        }))[0];
        if (!sessSetCookie) {
          callback("failed to login.");
          return;
        }
        sessId = (((sessSetCookie.split("; ")).filter(function(c, i) {
          return (c.indexOf("PHPSESSID")) === 0;
        }))[0].split("="))[1];
        return callback(null, new Session(sessId));
      });
    },
    getGrapichWork: function(session, workId, callback) {
      var params, url;
      params = makeQuery({
        p: 1,
        illust_id: workId,
        "PHPSESSID": session.sessionId
      });
      url = "" + pixiv.config.endpoints.apiBaseUrl + "/illust.php?" + params;
      return request.get({
        url: url
      }, function(error, resp, body) {
        if (error) {
          callback(error);
        }
        return callback(null, Work.parseSingle(body));
      });
    }
  };

  module.exports = pixiv;

}).call(this);
