// Generated by CoffeeScript 1.8.0
(function() {
  var Session;

  Session = (function() {
    function Session(sessId) {
      this.sessionId = sessId;
    }

    return Session;

  })();

  module.exports = Session;

}).call(this);
